
class Homophones {
  final Map<String, List<String>> homophones = {
    'accept': ['except'],
    'affect': ['effect'],
    'aisle': ['isle', "I'll"],
    'aloud': ['allowed'],
    'allowed': ['aloud'],
    'ate': ['eight'],
    'bare': ['bear'],
    'bean': ['been'],
    'been': ['bin'],
    'blew': ['blue'],
    'blue': ['blew'],
    'brake': ['break'],
    'break': ['brake'],
    'buy': ['by', 'bye'],
    'by': ['buy', 'bye'],
    'bye': ['buy', 'by'],
    'cell': ['sell'],
    'cent': ['scent', 'sent'],
    'dear': ['deer'],
    'days': ['daze'],
    'deer': ['dear'],
    'die': ['dye'],
    'dye': ['die'],
    'eight': ['ate'],
    'effect': ['affect'],
    'except': ['accept'],
    'fair': ['fare'],
    'fare': ['fair'],
    'fir': ['fur'],
    'flour': ['flower'],
    'flower': ['flour'],
    'for': ['fore', 'four'],
    'fore': ['for', 'four'],
    'four': ['for', 'fore'],
    'fur': ['fir'],
    'hear': ['here'],
    'here': ['hear'],
    'hole': ['whole'],
    'hour': ['our'],
    'idle': ['idol'],
    'idol': ['idle'],
    'I\'ll': ['aisle', 'isle'],
    'isle': ['aisle', 'I\'ll'],
    'knew': ['new'],
    'knows': ['nose'],
    'mail': ['male'],
    'maid': ['made'],
    'male': ['mail'],
    'made': ['maid'],
    'meat': ['meet'],
    'meet': ['meat'],
    'morning': ['mourning'],
    'mourning': ['morning'],
    'new': ['knew'],
    'nose': ['knows'],
    'our': ['hour'],
    'pair': ['pare', 'pear'],
    'pare': ['pair', 'pear'],
    'peace': ['piece'],
    'pear': ['pair', 'pare'],
    'piece': ['peace'],
    'principal': ['principle'],
    'principle': ['principal'],
    'rain': ['rein', 'reign'],
    'recogniser': ['recognizer'],
    'recognizer': ['recogniser'],
    'rein': ['rain', 'reign'],
    'reign': ['rain', 'rein'],
    'right': ['rite', 'write'],
    'rite': ['right', 'write'],
    'roll': ['role'],
    'role': ['roll'],
    'scene': ['seen'],
    'scent': ['cent', 'sent'],
    'sea': ['see'],
    'see': ['sea'],
    'sell': ['cell'],
    'sent': ['cent', 'scent'],
    'sita': ['cheetah'],
    'cheetah': ['sita'],
    'spirit': ['speech', 'speed'],
    'speech': ['spirit', 'speed', 'spit'],
    'some': ['sum'],
    'source': ['shores'],
    'shores': ['source'],
    'steel': ['steal'],
    'steal': ['steel'],
    'suite': ['sweet'],
    'sum': ['some'],
    'sweet': ['suite'],
    'tail': ['tale'],
    'tale': ['tail'],
    'their': ['there', "they're"],
    'there': ['their', "they're"],
    "they're": ['their', 'there'],
    'threw': ['through', 'thru'],
    'through': ['threw', 'thru'],
    'thru': ['threw', 'through'],
    'to': ['too', 'two'],
    'too': ['to', 'two'],
    'two': ['to', 'too'],
    'wait': ['weight'],
    'way': ['weigh'],
    'wear': ['ware', 'where'],
    'weather': ['whether'],
    'weigh': ['way'],
    'weight': ['wait'],
    'whether': ['weather'],
    'where': ['wear', 'ware'],
    'whole': ['hole'],
    'wood': ['would'],
    'won': ['one'],
    'would': ['wood'],
    'write': ['right', 'rite'],
    'you\'re': ['your'],
    'your': ['you\'re']
  };
}